### ISSUE TITLE
I can't run this thing -.-

### ISSUE THREAD

**Issue by Jpadilla1** [Carl1101/Carl1101.github.io#1]

**Comment by eluciano11** [comment]
deja de hacer aguajes!

**Comment by eluciano11** [comment]
Cuando lo corrí salió esto:

![Uploading boom.gif . . .]()

**Comment by eluciano11** [comment]
Salió esto cuando lo corrí...
![boom](https://cloud.githubusercontent.com/assets/6109151/6119221/5f9e80f8-b09c-11e4-864b-d8041b35a630.gif)

**Comment by Carl1101** [comment]
![f05da75d008fa1bebf2ae6e4e0750954](https://cloud.githubusercontent.com/assets/6116202/6119228/6e20f516-b09c-11e4-9967-4acbaf285411.jpg)
